# Week 1 Assignment - Julian Ruggiero

##### Link to my Github copy that contains the data (I already included the column names at the top of the file)

https://github.com/gitjuli/DAV-5400/blob/master/breast-cancer-wisconsin.data

#### Link to the original dataset general information:
https://archive.ics.uci.edu/ml/datasets/Breast+Cancer+Wisconsin+%28Original%29

#### The data file can be found here (breast-cancer-wisconsin.data file): 
https://archive.ics.uci.edu/ml/machine-learning-databases/breast-cancer-wisconsin/

#### The dataset names with further information can be found here: 
https://archive.ics.uci.edu/ml/machine-learning-databases/breast-cancer-wisconsin/breast-cancer-wisconsin.names

For week 1 assignemnt, I will use the breast-cancer-wisconsin data. I am interested in this dataset because it provides valuable information related to the breast cancer cell, such as its size, shape, and class. Despite there are some missing values, there are only 16 instances, denoted by "?", it also contains a good amount of records (699). My goal is to be able to answer these questions:

- Percentage of the cases that are benign and malign?
- For the malign cases, which is the cell behaviour in terms of its shape and size?
- What about the benign ones? which is their behaviour?
- Which are the main characteristics that differenciate a benign from a malign tumor?

Below I just tried to take a quick look at the dataset inside a pandas dataframe to be sure that I would be able to answer the questions above (I added the column's title I got from the breast-cancer-wisconsin.names file)

In [1]:
import pandas as pd
url="https://raw.githubusercontent.com/gitjuli/DAV-5400/master/breast-cancer-wisconsin.data" #using dataset raw data
df=pd.read_csv(url) #loading the data inside a dataframe

In [2]:
df.head() #a quick look to the first 5 rows of data to see how it looks like

,Sample code number,Clump Thickness,Uniformity of Cell Size,Uniformity of Cell Shape,Marginal Adhesion,Single Epithelial Cell Size,Bare Nuclei,Bland Chromatin,Normal Nucleoli,Mitoses,Class
0,1000025,5,1,1,1,2,1,3,1,1,2
1,1002945,5,4,4,5,7,10,3,2,1,2
2,1015425,3,1,1,1,2,2,3,1,1,2
3,1016277,6,8,8,1,3,4,3,7,1,2
4,1017023,4,1,1,3,2,1,3,1,1,2